# #####################################################################
# Automatically generated by qmake (2.01a) p� 9 9 19:59:56 2011
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += . \
    src
INCLUDEPATH += . \
    src
QT += core
QT += xml
QT -= qui

# Input
HEADERS += src/dateType.h \
    src/booleanType.h \
    src/attribute.h \
    src/attributeUse.h \
    src/complexType.h \
    src/element.h \
    src/elementUse.h \
    src/generator.h \
    src/listType.h \
    src/normalizer.h \
    src/numberType.h \
    src/objects.h \
    src/settings.h \
    src/simpleType.h \
    src/stringType.h \
    src/type.h \
    src/unionType.h \
    src/utils.h
SOURCES += src/dateType.cpp \
    src/booleanType.cpp \
    src/attribute.cpp \
    src/attributeUse.cpp \
    src/complexType.cpp \
    src/element.cpp \
    src/elementUse.cpp \
    src/generator.cpp \
    src/listType.cpp \
    src/main.cpp \
    src/normalizer.cpp \
    src/numberType.cpp \
    src/objects.cpp \
    src/settings.cpp \
    src/simpleType.cpp \
    src/stringType.cpp \
    src/type.cpp \
    src/unionType.cpp \
    src/utils.cpp
