# #####################################################################
# Automatically generated by qmake (2.01a) p� 9 2 20:45:15 2011
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += numberType.h \
    stringType.h \
    attribute.h \
    attributeUse.h \
    complexType.h \
    element.h \
    elementUse.h \
    generator.h \
    listType.h \
    normalizer.h \
    objects.h \
    settings.h \
    simpleType.h \
    type.h \
    unionType.h \
    utils.h
SOURCES += stringType.cpp \
    attribute.cpp \
    attributeUse.cpp \
    complexType.cpp \
    element.cpp \
    elementUse.cpp \
    generator.cpp \
    listType.cpp \
    main.cpp \
    normalizer.cpp \
    objects.cpp \
    settings.cpp \
    simpleType.cpp \
    type.cpp \
    unionType.cpp \
    utils.cpp
